Documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'

Github-files:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

Tests:
  - changed-files:
    - any-glob-to-any-file: 'src/tests/**'

Libinspector-Core:
  - changed-files:
    - any-glob-to-any-file: 'src/libinspector/**.py'

IEEE-files:
  - changed-files:
    - any-glob-to-any-file: 'src/libinspector/data/**.csv'
